spring:
  data:
    neo4j:
      uri: bolt://neo4j
      username: neo4j
      password: secret
  kafka:
    bootstrap-servers: apache-kafka:9092
      
      
management:
   endpoints:
      enabled-by-default: true
      web:
         exposure:
            include: '*'

app:
  topic: feed-item-complete      
